Refactor HTTP request handling into HttpAdapter class
vjik/telegram-bot-api pull request #116
Opened 2024-08-21 11:59 UTC by ankapone

- Implement the `HttpAdapter` class to encapsulate the logic for converting Telegram requests to HTTP requests.
- Update `PsrTelegramClient` to use `HttpAdapter` for handling requests.
- Enhance unit tests to verify the functionality of `HttpAdapter`.

2024-08-22 09:30 UTC, vjik commented
What is the purpose of these changes? Just refactoring?

2024-08-23 14:00 UTC, ankapone commented
The separation of responsibilities between the client (who actually makes the request) and the builder of that request, and, as a result, the simplification of testing. Well, you could say it's just a refactoring.

2024-08-31 06:20 UTC, vjik requested changes
Good refactoring, but it needs a few fixes.

2024-08-31 06:20 UTC, vjik commented on src/Client/HttpAdapter.php
> +final readonly class HttpAdapter
```suggestion
/**
 * @internal
 */
final readonly class PsrRequestFactory
```

2024-08-31 06:20 UTC, vjik commented on src/Client/PsrTelegramClient.php
Add tests for this class also.

2024-09-05 14:17 UTC, closed without merging